@startuml Rental (GET ONE)

header SuperCarcare Rental  Diagram
footer Page %page% of %lastpage%
title "Working Rental (GET ONE)"

participant "Client" as client
participant "<<javaScript>>\n:server" as server
participant "<<router>>\n:rentals" as routerRentals
participant "<<controllers>>\n:rentals" as controllersRentals
participant "<<model>>\n:Rental" as modelRentals
database "<<MongoDB>>\n:rentals" as RentalsDatabase

client->server ++:req.get('/rentals/:id')
server->routerRentals ++:app.use('/rentals',rentals)
routerRentals -> controllersRentals ++:getRental()
controllersRentals->modelRentals ++:findById(req.params.id)
modelRentals ->RentalsDatabase ++: RentalSchema
RentalsDatabase --> modelRentals --: rental
controllersRentals <-- modelRentals --:rental
controllersRentals->client --:response

@enduml